apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJiV0Y0YVcxd2IyUTZaMmh3WDNwNlEzcHJOMUJwTTJkR1pXRkhRa1ZFUVZwbmEwaEdWemRrY0Voc1NUQmhTbGx3WVE9PSJ9fX0K
  #ewoJImF1dGhzIjogeJCQkiYXV0aCI6ICJaR0W10aFVXbFZSbTVaKCSJmZWF0dXJlcyI6IHsKCQkiaG9va3MiOiAidHJ1ZSIKCX0KfQ==
type: kubernetes.io/dockerconfigjson
